# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljXqEV8RVktMIyH-WGLNzUqmKFQMBSQ-

#Mount to Drive/ Set libraries
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/KAIST/25_01/NLP

!pip install nltk konlpy wordcloud matplotlib
# Changing NumPy version for Gensim use
!pip install numpy==1.26.4 -q
!pip install gensim -q
!pip install bertopic -q
!pip install pyLDAvis -q
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!After executing this cell, go to Menu -> Runtime -> Restart session!!!!!!!!!!!!!!!!!!!!!!
!pip install bertopic

import pandas as pd
from konlpy.tag import Okt
import re
from nltk.corpus import stopwords
from gensim import corpora, models
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis
import matplotlib.pyplot as plt
import nltk
from nltk import FreqDist

"""# Weverse"""

# 1. Load CSV
df = pd.read_csv("weverse_full.csv")
df = df.dropna(subset=["content"])
texts = df["content"].tolist()

df

# 2. Initialize tokenizer
okt = Okt()
nltk.download("stopwords")

# 3. Preprocess function
def clean_text(text):
    text = re.sub(r'[^\uAC00-\uD7A3\s]', '', text)  # remove non-Korean
    tokens = okt.nouns(text)
    stop_words = set(stopwords.words('korean')) if 'korean' in stopwords.fileids() else set()
    return [t for t in tokens if len(t) > 1 and t not in stop_words]

# 4. Apply preprocessing
cleaned_texts = [clean_text(text) for text in texts]
cleaned_texts = [text for text in cleaned_texts if len(text) > 0]

# 5. Create dictionary and corpus
dictionary = corpora.Dictionary(cleaned_texts)
corpus = [dictionary.doc2bow(text) for text in cleaned_texts]

# 6. LDA modeling
lda_model = models.LdaModel(corpus, num_topics=5, id2word=dictionary, passes=10, random_state=42)

# 7. Show topics
for idx, topic in lda_model.print_topics(-1):
    print(f"Topic {idx}: {topic}")

# 8. Visualize with pyLDAvis
pyLDAvis.enable_notebook()
vis = gensimvis.prepare(lda_model, corpus, dictionary)
vis

"""## Complex version"""

# Step 1: Advanced preprocessing setup
okt = Okt()

# Fan slang normalization dictionary
fan_slang_dict = {
    "스밍": "스트리밍",
    "플리": "팬",
    "재화": "포인트",
    "우주폰": "스밍폰",
    "공폰": "공용폰",
    "사과폰": "아이폰",
    "심괴": "심야괴담회",
    "멤버": "멤버",
    "뉴플리": "팬",
    "탈탈탈": "완전"
}

# Custom stopwords (expandable later)
custom_stopwords = set([
    "정말", "그리고", "이번", "오늘", "내일", "하는", "있어요", "했습니다",
    "자기", "지금", "조금", "같아요", "ㅠㅠ", "ㅎㅎ", "ㅋㅋ", "더보기",
    "하다", "있다", "보다","보기","들다","너무","되다","이다","우리","해주다",
    "으로","진짜","수고","같다","아니다","완료","자다","많이","않다",'오다','하고','없다',
    '까지','쓰다','그렇다','가다','해보다','싶다','알다','받다'
])

# Function to clean and normalize text
def preprocess_text(text):
    text = re.sub(r"[^\w\s]", " ", text)  # remove punctuation/symbols
    text = re.sub(r"\s+", " ", text)  # normalize spaces
    text = re.sub(r"(.)\1{2,}", r"\1", text)  # reduce repeated characters
    for slang, norm in fan_slang_dict.items():
        text = text.replace(slang, norm)
    return text.strip()

# Apply preprocessing
df["cleaned"] = df["content"].apply(preprocess_text)

# Tokenization with Okt
df["tokens"] = df["cleaned"].apply(lambda x: [word for word in okt.morphs(x, stem=True)
                                              if word not in custom_stopwords and len(word) > 1])
# Flatten and show top 50 frequent tokens for optional stopword refinement
all_tokens = sum(df["tokens"].tolist(), [])
fdist = FreqDist(all_tokens)
top_50_words = fdist.most_common(50)

df["tokens_noun"] = df["cleaned"].apply(lambda x: [w for w, t in okt.pos(x) if t in ['Noun', 'Adjective'] and w not in custom_stopwords])

# Gensim LDA
from gensim import corpora, models

# Prepare dictionary and corpus
dictionary = corpora.Dictionary(df["tokens"])
corpus = [dictionary.doc2bow(text) for text in df["tokens"]]

# Train LDA model
lda_model = models.LdaModel(corpus=corpus, id2word=dictionary, num_topics=5, passes=10)

# Show topics
topics = lda_model.print_topics(num_words=10)
for i, topic in topics:
    print(f"Topic {i}: {topic}")

from bertopic import BERTopic
topic_model = BERTopic(language="multilingual")
topics, probs = topic_model.fit_transform(df["cleaned"])
topic_model.get_topic_info()

topic_model.get_topic_info()

"""# Youtube"""

# 1. Load CSV
df = pd.read_csv("plave_youtube_full.csv")
df = df.dropna(subset=["comment"])
texts = df["comment"].tolist()
df

# 2. Filter only comments published in April–May 2025
df['published'] = pd.to_datetime(df['published'])
df_filtered = df[(df['published'] >= "2025-04-01") & (df['published'] <= "2025-05-31")]

# 3. Keep only comments that contain Korean characters
def contains_korean(text):
    return bool(re.search(r"[가-힣]", text))

df = df_filtered[df_filtered["comment"].apply(contains_korean)]
df

# 2. Initialize tokenizer
okt = Okt()
nltk.download("stopwords")

# 3. Preprocess function
def clean_text(text):
    text = re.sub(r'[^\uAC00-\uD7A3\s]', '', text)  # remove non-Korean
    tokens = okt.nouns(text)
    stop_words = set(stopwords.words('korean')) if 'korean' in stopwords.fileids() else set()
    return [t for t in tokens if len(t) > 1 and t not in stop_words]

# 4. Apply preprocessing
cleaned_texts = [clean_text(text) for text in texts]
cleaned_texts = [text for text in cleaned_texts if len(text) > 0]

# 5. Create dictionary and corpus
dictionary = corpora.Dictionary(cleaned_texts)
corpus = [dictionary.doc2bow(text) for text in cleaned_texts]

# 6. LDA modeling
lda_model = models.LdaModel(corpus, num_topics=5, id2word=dictionary, passes=10, random_state=42)

# 7. Show topics
for idx, topic in lda_model.print_topics(-1):
    print(f"Topic {idx}: {topic}")

# 8. Visualize with pyLDAvis
pyLDAvis.enable_notebook()
vis = gensimvis.prepare(lda_model, corpus, dictionary)
vis

# 1. Install NanumGothic font and reload matplotlib
!apt-get -qq install fonts-nanum
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
plt.rc('font', family='NanumGothic')  # Set global font to NanumGothic
plt.rcParams['axes.unicode_minus'] = False  # Fix minus sign display

# 2. Imports
import pandas as pd
import re
from wordcloud import WordCloud
from datetime import datetime

df_filtered=df
# 6. Merge comments
text_data = " ".join(df_filtered["comment"].astype(str).tolist())

from collections import Counter

# 7. Clean text: remove emojis, symbols, keep Korean
def clean_text(text):
    text = re.sub(r"[^\uAC00-\uD7A3\s]", " ", text)  # keep only Korean
    text = re.sub(r"\s+", " ", text)
    return text.strip()

cleaned_text = clean_text(text_data)

# 8. Tokenize and filter
tokens = cleaned_text.split()

# Define words/phrases to exclude
excluded_words = set([
    "아니", "플레이브", "넘", "귀엽다", "정말", "오늘", "진짜", "그냥", "그거", "ㅋㅋ", "ㅎㅎ", "ㅠㅠ",'너무','미친','우리','하미니'
])

# Filter out: one-character + excluded words
filtered_tokens = [w for w in tokens if len(w) > 1 and w not in excluded_words]

# Count frequency
word_freq = Counter(filtered_tokens)

# 9. Generate word cloud
wordcloud = WordCloud(
    font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',
    background_color='white',
    width=800,
    height=600
).generate_from_frequencies(word_freq)

# 10. Plot
plt.figure(figsize=(10, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("📊 YouTube WordCloud (Korean, Apr–May 2025, Filtered)", fontsize=16)
plt.show()

"""## Complex version"""

from sentence_transformers import SentenceTransformer


# Step 3: Fan slang normalization and custom stopwords
fan_slang_dict = {
    "스밍": "스트리밍", "플리": "팬", "재화": "포인트", "우주폰": "스밍폰",
    "공폰": "공용폰", "사과폰": "아이폰", "심괴": "심야괴담회",
    "멤버": "멤버", "뉴플리": "팬", "탈탈탈": "완전"
}

custom_stopwords = set([
    "정말", "그리고", "이번", "오늘", "내일", "하는", "있어요", "했습니다",
    "자기", "지금", "조금", "같아요", "ㅠㅠ", "ㅎㅎ", "ㅋㅋ", "더보기"
])

# Step 4: Preprocessing function
okt = Okt()

def preprocess_text(text):
    text = re.sub(r"[^\w\s]", " ", text)              # remove symbols/punctuation
    text = re.sub(r"\s+", " ", text)                  # normalize spaces
    text = re.sub(r"(.)\1{2,}", r"\1", text)          # reduce repeated chars
    for slang, norm in fan_slang_dict.items():
        text = text.replace(slang, norm)
    return text.strip()

# Apply preprocessing
df["cleaned"] = df["comment"].apply(preprocess_text)

# Tokenization + stopword filtering
df["tokens"] = df["cleaned"].apply(lambda x: [word for word in okt.morphs(x, stem=True)
                                              if word not in custom_stopwords and len(word) > 1])

# Re-join tokens into cleaned text (needed for BERTopic)
df["final_text"] = df["tokens"].apply(lambda x: " ".join(x))

# Step 5: Topic modeling with BERTopic
embedding_model = SentenceTransformer("snunlp/KR-SBERT-V40K-klueNLI-augSTS")  # Korean SBERT

from bertopic import BERTopic
from hdbscan import HDBSCAN

# Optional: pre-cleaned and tokenized text from previous step
cleaned_docs = df["tokens"].apply(lambda x: ' '.join(x)).tolist()

# HDBSCAN setup
hdbscan_model = HDBSCAN(min_cluster_size=30, min_samples=5, metric='euclidean')

# Topic model
topic_model = BERTopic(language="multilingual",
                       hdbscan_model=hdbscan_model,
                       top_n_words=8)
topics, probs = topic_model.fit_transform(cleaned_docs)

# Reduce number of topics for interpretability
topic_model.reduce_topics(cleaned_docs, nr_topics=10)

# View topics
topic_info = topic_model.get_topic_info()
topic_model.visualize_barchart(top_n_topics=10)

topic_info

